services:
  backend:
    extends:
      file: ./backend/docker-compose.backend.yml
      service: web

  celery:
    extends:
      file: ./backend/docker-compose.backend.yml
      service: celery

  beat:
    extends:
      file: ./backend/docker-compose.backend.yml
      service: beat

  redis:
    extends:
      file: ./backend/docker-compose.backend.yml
      service: redis

  frontend:
    extends:
      file: ./frontend/docker-compose.frontend.yml
      service: frontend
