# Generated by Django 5.2.10 on 2026-03-03 20:13

import apis.board_ai_assistant.services.encryption_field
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board_ai_assistant', '0001_enable_pgvector'),
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('api_key', apis.board_ai_assistant.services.encryption_field.EncryptedTextField()),
                ('base_url', models.URLField(default='https://openrouter.ai/api/v1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardAIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='board_ai_assistant.boardaichat')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'created_at'], name='board_ai_as_chat_id_abf0e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoardMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('memory_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')])),
                ('is_pinned', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memories', to='boards.board')),
            ],
            options={
                'indexes': [models.Index(fields=['board', 'is_pinned', 'memory_type'], name='board_ai_as_board_i_9ce251_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='memory_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
